[tools]
cmake = "latest"

[tasks.clear-qmlcache]
run = "rm -rf contents/ui/*.qmlc"
description = "Clear QML cache and compiled QML files"

[tasks.build]
run = "scripts/install-local.sh"
description = "Install local build"
