name: Community Screenshot Submission
description: Share your setup with the community!
title: '[Screenshot] My Setup'
labels: '📸 Community Screenshot'
body:
  - type: upload
    id: screenshot
    attributes:
      label: Screenshot
      description: Upload a screenshot of your setup showcasing Modern reClock in action. (Max 5MB)
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Tell us a bit about your setup, what you like about Modern reClock, or any customizations you've made. (Optional)
    validations:
      required: false
